apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-w08e1
  labels:
    app: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: customers
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-w08e1
  labels:
    app: customer-db
spec:
  selector:
    app: customer-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
