# week08/k8s/product-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: product-service
          image: nginx:1.25  # replaced by workflow with your image
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: product-db-service-w08e1
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_PASSWORD

            # Optional storage envs if your app uses uploads
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: AZURE_STORAGE_ACCOUNT_KEY
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1
                  key: AZURE_STORAGE_CONTAINER_NAME

          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
