name: Deploy to Staging

on:
  workflow_run:
    workflows: ["CI Testing"]   
    types:
      - completed

jobs:
  deploy:
    # Only run if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Add your build/deploy steps here
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name smahweek10

      - name: Build and push Docker image
        run: |
          docker build -t smahweek10.azurecr.io/frontend:staging ./frontend
          docker push smahweek10.azurecr.io/frontend:staging

      - name: Deploy to AKS (Staging)
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
      - run: |
          kubectl -n staging set image deploy/frontend frontend=smahweek10.azurecr.io/frontend:staging
          kubectl -n staging rollout status deploy/frontend
