name: CD Pipeline - Deploy to Production

on:
  push:
    branches:
      - main   # Only trigger on production branch

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Validate that required secrets exist
      - name: Validate inputs
        env:
          AZ_RG: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZ_AKS: ${{ secrets.AZURE_AKS_CLUSTER }}
        run: |
          if [ -z "$AZ_RG" ]; then echo "❌ Missing secret: AZURE_RESOURCE_GROUP"; exit 1; fi
          if [ -z "$AZ_AKS" ]; then echo "❌ Missing secret: AZURE_AKS_CLUSTER"; exit 1; fi
          echo "✅ Resource Group: $AZ_RG"
          echo "✅ AKS Cluster: $AZ_AKS"

      # Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name "${{ secrets.AZURE_AKS_CLUSTER }}" \
            --overwrite-existing

          # If you don’t want to use secrets, hardcode instead:
          # az aks get-credentials \
          #   --resource-group deakinuni \
          #   --name smahweek10 \
          #   --overwrite-existing

      # Deploy manifests
      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/

      # Wait until pods are ready
      - name: Wait for pods
        run: |
          # If your workloads are in 'prod' namespace, add: -n prod
          kubectl wait --for=condition=Ready pods --all --timeout=300s
