name: CD Pipeline - Deploy to Staging (Fast + Tiny Test)

on:
  push:
    branches:
      - staging   # Runs only when code is pushed/merged into staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    environment:
      name: staging

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      # Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name "${{ secrets.AZURE_AKS_CLUSTER }}" \
            --overwrite-existing

      # Create staging namespace (if not exists)
      - name: Create staging namespace
        run: |
          kubectl get ns staging >/dev/null 2>&1 || kubectl create namespace staging

      # Deploy to staging
      - name: Deploy manifests
        run: |
          kubectl apply -n staging -f k8s/

      # Short rollout wait to keep things snappy
      - name: Wait for deployments to be Available (short)
        run: |
          set -e
          kubectl -n staging get deploy -o name \
          | xargs -r -I{} kubectl -n staging rollout status {} --timeout=120s

      # Tiny acceptance test (very fast):
      # Assert that every Se
